### ISSUE TITLE
new games?

### ISSUE THREAD

**Issue by deividbinev12** [Tsyuay/FrivReborn#5]
you added papa louie 2 and papa louie 3?

**Comment by Tsyuay** [comment]
Hello, sorry for the delay but yes, I added them to replace Sonic the Hedgehog and Super Mario Bros because of copyright issues. This almost happened to the original classic Friv because of adding these games and in the development of Friv Reborn I was worried because of that so I had to replace them.

**Comment by ClassicFriv** [comment]
Plz add Sara's sweet cooking class

**Comment by Frivclassic** [comment]
@Tsyuay Please add Sara's sweet cooking class

**Comment by Frivclassic** [comment]
The [Link][Playsara.com]is this one just click on any games and if it says flash is not working just click the "run anyway" button

**Comment by Frivclassic** [comment]
[Playsara.com](Playsara.com) is the link. If it says flash player is not working anymore, just click the run anyway button.

**Comment by Tsyuay** [comment]
done
